
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MiniAttandanceSystem
{

using System;
    using System.Collections.Generic;
    
public partial class StudentAttandance
{

    public int Id { get; set; }

    public Nullable<int> StudentId { get; set; }

    public Nullable<System.DateTime> AttandanceDate { get; set; }



    public virtual Student Student { get; set; }

}

}
